name: CI
on: push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Lint & Format
        run: |
          deno lint
          deno fmt --check
      - name: Test
        run: deno test

